name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          MOLLIE = ${{ secrets.MOLLIE }}
          MOLLIE_ACCESS = ${{ secrets.MOLLIE_ACCESS }}


      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/bap24
            git pull origin main && npm install && npm run build && pm2 restart mafia