
name: Deploy to Server

on:
  push:
    branches:
      - main

defaults:
 run:
  working-directory: ./BAP24

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx prisma generate && npm run build
        env:
          MOLLIE: ${{ secrets.MOLLIE }}
          MOLLIE_ACCESS: ${{ secrets.MOLLIE_ACCESS }}
          
      - name: Check
        env:
          HOST: ${{ secrets.SSH_HOST }}
        run: echo "Deploying to $HOST"

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd ~/bap24
            git pull origin main && npm install && npm run build && pm2 restart server
          "