
name: Deploy to Server

on:
  push:
    branches:
      - main

defaults:
 run:
  working-directory: ./BAP24

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx prisma generate
          
      - name: Check
        env:
          HOST: ${{ secrets.SSH_HOST }}
        run: echo "Deploying to $HOST"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            cd ~/BAP24
            git pull origin main && npm install && npm run build && pm2 restart server